- name: Install fnm globally
  block:
    - name: Check if fnm is already installed
      ansible.builtin.stat:
        path: "/usr/local/bin/fnm"
      register: fnm_binary

    - name: Provision fnm
      when: not fnm_binary.stat.exists
      block:
        - name: Download fnm archive
          ansible.builtin.get_url:
            url: "https://github.com/Schniz/fnm/releases/download/v1.39.0/fnm-linux.zip"
            dest: "/tmp/fnm-linux.zip"
            checksum: "sha256:7807664f39d39fc518da1c35ba0181e4b3267603c4b1dedeb4b5fc6ae440a224"
            mode: '0644'

        - name: Extract fnm binary to /usr/local/bin
          ansible.builtin.unarchive:
            src: "/tmp/fnm-linux.zip"
            dest: "/usr/local/bin"
            remote_src: true
            creates: "/usr/local/bin/fnm"
          become: true

        - name: Ensure correct permissions
          ansible.builtin.file:
            path: "/usr/local/bin/fnm"
            owner: root
            group: root
            mode: '0755'
          become: true

        - name: Cleanup temporary zip
          ansible.builtin.file:
            path: "/tmp/fnm-linux.zip"
            state: absent

