- name: Install fnm globally
  when: fnm_version is not none
  block:
    - name: Set fnm archive name
      ansible.builtin.set_fact:
        fnm_archive: "{{ (ansible_architecture == 'x86_64') | ternary('fnm-linux.zip', 'fnm-arm64.zip') }}"

    - name: Check if fnm is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/fnm
      register: fnm_binary

    - name: Provision fnm
      when: not fnm_binary.stat.exists
      block:
        - name: Download fnm archive
          ansible.builtin.get_url:
            url: "https://github.com/Schniz/fnm/releases/download/v{{ fnm_version }}/{{ fnm_archive }}"
            dest: "/tmp/{{ fnm_archive }}"
            mode: "0644"

        - name: Verify fnm checksum
          ansible.builtin.shell: echo "{{ fnm_checksums }}" | grep '{{ fnm_archive }}' | sha256sum -c
          args:
            chdir: /tmp

        - name: Extract fnm binary to /usr/local/bin
          become: true
          ansible.builtin.unarchive:
            src: "/tmp/{{ fnm_archive }}"
            dest: /usr/local/bin
            remote_src: true
            creates: /usr/local/bin/fnm

        - name: Ensure correct permissions
          become: true
          ansible.builtin.file:
            path: /usr/local/bin/fnm
            owner: root
            group: root
            mode: "0755"

        - name: Cleanup temporary zip
          ansible.builtin.file:
            path: "/tmp/{{ fnm_archive }}"
            state: absent
