- name: Ensure dependencies
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - stow
      - fzf
      - zoxide
      - ripgrep
      - unzip
    state: present
    update_cache: yes

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/MrkMrk00/dotfiles"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    version: master
    update: no
    accept_hostkey: yes

- name: Stow all dotfiles
  ansible.builtin.shell: stow .
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/dotfiles"

- name: Install fnm
  ansible.builtin.include_tasks: ./fnm.yaml

- name: Install opencode
  ansible.builtin.include_tasks: ./opencode.yaml
