- name: Install basic packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - vim
      - ca-certificates
      - sudo
      - xz-utils
    state: present

- name: Install Docker
  ansible.builtin.include_tasks: docker.yaml
