- name: Provision Dev VM system tools
  hosts: local
  become: true
  gather_facts: true
  roles:
    - common
    - docker

- name: Provision Dev VM dev tools
  hosts: local
  become: false
  gather_facts: true
  roles:
    - nvm
    - dotfiles
    - work
