- name: Provision Dev VM system tools
  become: true
  hosts: all
  gather_facts: true
  vars_files:
    - vars/versions.yaml
  roles:
    - system

- name: Provision Dev VM dev tools
  hosts: all
  become: false
  gather_facts: true
  vars_files:
    - vars/versions.yaml
  roles:
    - user
